### ISSUE TITLE
Wants direct access to  "classnames.txt"  file.

### ISSUE THREAD

**Issue by gbljdgb** [sfimediafutures/CLIPping-the-Deception#5]
Greetings, esteemed author.
I am very interested in your work, but I can't re-download the dataset because it is too big, I have the dataset locally but not the classnames.txt, so I hope I can get the classnames.txt file directly, thanks.

**Comment by sohailahmedkhan** [comment]
hi. please find the file attached.

[classnames.txt](https://github.com/user-attachments/files/17607754/classnames.txt)

**Comment by gbljdgb** [comment]
> hi. please find the file attached.
> 
> [classnames.txt](https://github.com/user-attachments/files/17607754/classnames.txt)

Thank You!!!
